/**
 * Types and a flattener for Playwright's **raw** JSON reporter document (#801).
 *
 * ## Why this is not `parsePlaywrightReport`
 *
 * The existing parser (and its Python twin `parse_playwright_report`) flattens a
 * report to one row per spec and keeps `results[results.length - 1]`. That is the
 * right shape for "did this spec pass", and exactly the wrong one for a report
 * viewer: it discards the **steps** tree, the per-**retry** results, stdout/stderr
 * and — because it recomputes an outcome from the final result — Playwright's
 * **flaky** category, which is precisely a test whose last result passed. So this
 * module reads the raw document instead and never recomputes an outcome:
 * {@link PwTest.status} is Playwright's own verdict and the summary comes from the
 * report's own {@link PwStats}.
 *
 * ## Shape verified against Playwright 1.61.1
 *
 * The repo pins `@playwright/test@^1.61.1` in both `app/` and `agent/`, and this
 * module's optionality mirrors a report generated by that exact version — the
 * reporter's payload has shifted between releases, and a viewer built on an
 * assumed shape fails as a blank panel rather than as an error. Findings that
 * drive the types below:
 *
 * - A **skipped** result carries **no `steps` key at all** (and no `error`), so
 *   `steps` must be optional — `result.steps.map(...)` would throw on the first
 *   skipped test in any suite.
 * - A step is `{ title, duration, steps? }` only; there is no `category`,
 *   `location` or `startTime` in this version's output. `error` is declared
 *   optional because a failing step carries one, but nothing may rely on it.
 * - `error.message`, `error.stack` and `error.snippet` are **ANSI-coloured**
 *   (`[31m…`). Rendered verbatim they show as `[31m` litter, hence
 *   {@link stripAnsi}.
 * - `result.attachments[].path` is an **absolute path on the machine that ran the
 *   test** — the paired device, usually. It is never fetchable from the browser,
 *   which is why the viewer's attachments come from `Evidence` rows instead.
 * - Suites nest: a file-level suite may hold `suites` (one per `describe`) as well
 *   as `specs`, so the walk has to recurse.
 */

/** Playwright's computed verdict for a test, across all of its retries. */
export type PwTestStatus = "expected" | "unexpected" | "flaky" | "skipped";

/** The outcome buckets the viewer filters on — a 1:1 renaming of {@link PwTestStatus}. */
export type ReportOutcome = "passed" | "failed" | "flaky" | "skipped";

export interface PwLocation {
  file: string;
  line: number;
  column: number;
}

export interface PwError {
  message?: string;
  stack?: string;
  location?: PwLocation;
  /** The code frame around the failure. Present for assertion failures. */
  snippet?: string;
  value?: string;
}

/** One entry of a result's `stdout` / `stderr`. Playwright emits `{text}` or `{buffer}`. */
export interface PwStream {
  text?: string;
  buffer?: string;
}

export interface PwAttachment {
  name: string;
  contentType: string;
  /** Absolute path **on the runner**, not on this machine. See the module note. */
  path?: string;
  body?: string;
}

/** A step of a result. Nested via `steps`; `duration` is milliseconds. */
export interface PwStep {
  title: string;
  duration?: number;
  steps?: PwStep[];
  error?: PwError;
}

/** One attempt at a test — `retry: 0` is the first run. */
export interface PwResult {
  workerIndex?: number;
  parallelIndex?: number;
  status?: string;
  duration?: number;
  error?: PwError;
  errors?: PwError[];
  stdout?: PwStream[];
  stderr?: PwStream[];
  retry?: number;
  /** Absent entirely on a skipped result — see the module note. */
  steps?: PwStep[];
  startTime?: string;
  attachments?: PwAttachment[];
  errorLocation?: PwLocation;
}

/** One (spec × project) pair. `status` is Playwright's verdict, never recomputed. */
export interface PwTest {
  timeout?: number;
  expectedStatus?: string;
  projectId?: string;
  projectName?: string;
  status?: PwTestStatus;
  results?: PwResult[];
}

export interface PwSpec {
  title: string;
  ok?: boolean;
  tags?: string[];
  id?: string;
  file: string;
  line?: number;
  column?: number;
  tests?: PwTest[];
}

export interface PwSuite {
  title?: string;
  file?: string;
  line?: number;
  column?: number;
  specs?: PwSpec[];
  suites?: PwSuite[];
}

/** The report's own counters. The summary bar reads these and adds nothing. */
export interface PwStats {
  startTime?: string;
  duration?: number;
  expected?: number;
  unexpected?: number;
  flaky?: number;
  skipped?: number;
}

/** The whole `report.json`, as `GET /executions/{id}/report` serves it. */
export interface PwJsonReport {
  config?: { version?: string; rootDir?: string };
  suites?: PwSuite[];
  errors?: PwError[];
  stats?: PwStats;
}

/** One row of the viewer's test list — a test, with everything it needs to render. */
export interface ReportTest {
  /** Stable within one report; what `?case=`-style selection holds. */
  key: string;
  /** Spec path as the report records it, relative to Playwright's `rootDir`. */
  file: string;
  /** Titles of the `describe` blocks between the file and the test, outermost first. */
  suitePath: string[];
  /** The test's own title, without its describe path. */
  title: string;
  line: number;
  column: number;
  /** The Playwright project (usually the browser) this test ran under. */
  projectName: string;
  outcome: ReportOutcome;
  /** The last attempt's duration — what Playwright's own report shows per row. */
  durationMs: number;
  /** Every attempt, oldest first. `length > 1` means the test was retried. */
  results: PwResult[];
}

const OUTCOME_BY_STATUS: Record<PwTestStatus, ReportOutcome> = {
  expected: "passed",
  unexpected: "failed",
  flaky: "flaky",
  skipped: "skipped",
};

/** Every outcome bucket, in the order the filter renders them. */
export const REPORT_OUTCOMES: ReportOutcome[] = ["passed", "failed", "flaky", "skipped"];

// CSI sequences, which is all Playwright emits (SGR colour runs).
const ANSI = /\u001B\[[0-?]*[ -\/]*[@-~]/g;

/**
 * Drop ANSI escape sequences from reporter text.
 *
 * `error.message`, `error.stack` and `error.snippet` are colourised for a
 * terminal; in the DOM the escapes render as `[31m` noise that breaks up the
 * very code frame the reader is trying to read.
 */
export function stripAnsi(text: string): string {
  return text.replace(ANSI, "");
}

/**
 * Join a `stdout` / `stderr` array into one block of text.
 *
 * Entries are `{text}` in practice; `{buffer}` (base64) is accepted defensively
 * and rendered as-is rather than decoded — it is not something Playwright's JSON
 * reporter produces for console output.
 */
export function streamText(stream: PwStream[] | undefined): string {
  if (!stream || stream.length === 0) return "";
  return stripAnsi(stream.map((s) => s.text ?? s.buffer ?? "").join(""));
}

/**
 * Flatten a raw report into one {@link ReportTest} per (spec × project).
 *
 * Recurses through nested `suites` (a `describe` becomes a child suite) and
 * carries the describe titles down as {@link ReportTest.suitePath}, so a row can
 * show where a test lives without re-deriving it from the title.
 *
 * A test with no `status` is treated as `skipped` rather than dropped: an
 * unknown verdict is still a test that exists, and silently omitting rows is how
 * a viewer lies about a suite's size.
 */
export function flattenReport(report: PwJsonReport | undefined): ReportTest[] {
  const out: ReportTest[] = [];
  const walk = (suites: PwSuite[] | undefined, describes: string[]) => {
    for (const suite of suites ?? []) {
      // The file-level suite's title is the filename; a `describe`'s is its name.
      // Only the latter belongs in the describe path.
      const isFileSuite = !!suite.file && suite.title === suite.file;
      const nested = isFileSuite || !suite.title ? describes : [...describes, suite.title];
      for (const spec of suite.specs ?? []) {
        for (const [index, test] of (spec.tests ?? []).entries()) {
          const results = [...(test.results ?? [])].sort(
            (a, b) => (a.retry ?? 0) - (b.retry ?? 0),
          );
          const last = results[results.length - 1];
          out.push({
            key: `${spec.id ?? `${spec.file}:${spec.line}:${spec.title}`}#${test.projectId ?? index}`,
            file: spec.file,
            suitePath: nested,
            title: spec.title,
            line: spec.line ?? 0,
            column: spec.column ?? 0,
            projectName: test.projectName ?? test.projectId ?? "",
            outcome: OUTCOME_BY_STATUS[test.status ?? "skipped"] ?? "skipped",
            durationMs: last?.duration ?? 0,
            results,
          });
        }
      }
      walk(suite.suites, nested);
    }
  };
  walk(report?.suites, []);
  return out;
}

/** Per-outcome counts taken from the report's own `stats` — never recomputed. */
export function outcomeCounts(stats: PwStats | undefined): Record<ReportOutcome, number> {
  return {
    passed: stats?.expected ?? 0,
    failed: stats?.unexpected ?? 0,
    flaky: stats?.flaky ?? 0,
    skipped: stats?.skipped ?? 0,
  };
}

/** `1.4s` / `820ms` / `2m 05s` — compact, like Playwright's own report. */
export function formatDuration(ms: number | undefined): string {
  const value = Math.max(0, Math.round(ms ?? 0));
  if (value < 1000) return `${value}ms`;
  if (value < 60_000) return `${(value / 1000).toFixed(1)}s`;
  const minutes = Math.floor(value / 60_000);
  const seconds = Math.round((value % 60_000) / 1000);
  return `${minutes}m ${String(seconds).padStart(2, "0")}s`;
}

/**
 * Does `specPath` (an `ExecutionResult.spec_path`, repo-relative) name `file`
 * (the report's `rootDir`-relative path)?
 *
 * The two are relative to different roots — the runner's `testDir` is a
 * subdirectory of the staged repo — so an equality test would match nothing.
 * Falls back to a basename match, which is what makes the failure screenshot for
 * `tests/SUR-12/login.spec.ts` reachable from the report's `login.spec.ts`.
 */
export function specPathMatches(specPath: string, file: string): boolean {
  const a = specPath.replace(/\\/g, "/");
  const b = file.replace(/\\/g, "/");
  if (a === b) return true;
  if (a.endsWith(`/${b}`) || b.endsWith(`/${a}`)) return true;
  return a.split("/").pop() === b.split("/").pop();
}
