/**
 * E2E spec — generated by automation-generator
 * ---------------------------------------------------------------------------
 * Source ticket : <ADO/Jira ID>
 * Test Case ID  : <TC-NN>
 *
 * Layered spec. It lives in the project's automation project at
 * tests/<TICKET-ID>/<TICKET-ID>-<TC-NN>.spec.ts — TWO levels below the project
 * root — and sits on the shared base framework:
 *
 *   - Always import test/expect/helpers from '@q-agent/playwright-base'
 *     (never '@playwright/test'). That `test` carries evidence capture and the
 *     run's saved session, so the spec starts AUTHENTICATED — no inline login.
 *   - A shared project file is imported as '../../pages/Foo', but ONLY when the
 *     AUTOMATION PLAN block lists it as importable — that list was verified
 *     against the project's real tree. Never invent such an import: the
 *     project-wide `playwright test --list` gate rejects the spec if it does not
 *     resolve.
 *   - Locators live in those page objects; an inline locator here is the
 *     EXCEPTION, taken only for a step whose asset the plan lists as NOT ON DISK.
 * ---------------------------------------------------------------------------
 */
import { test, expect } from '@q-agent/playwright-base';

test('<TC-NN> — <test case title>', async ({ page }) => {
  // --- Arrange --- the session is already authenticated: go straight to the
  // route the case starts on (real route from the project context). Do NOT
  // generate a login preamble unless the case's subject IS authentication.
  await page.goto('<real route from context>');

  // --- Act --- one business step per test-case step, using KB-known selectors
  // (prefer data-testid / getByRole / getByLabel over raw CSS). Locators belong
  // in a page object once one exists for this screen.
  await page.getByRole('button', { name: '<real action from the case step>' }).click();

  // --- Assert --- one web-first assertion per Expected Result. Rely on
  // Playwright's auto-waiting — never page.waitForTimeout(...).
  await expect(page.getByText('<expected result text>')).toBeVisible();
});
